/**
 * The 105-task German SRC (Short Range Certificate / Beschraenkt
 * Gueltiges Funkbetriebszeugnis) practical-exam catalog, parsed from
 * docs/Test_questions (Comprehensive Pruefungs- und Validierungssystematik
 * fuer SRC-Seefunksimulatoren). Kept in German, matching the source and
 * the DSV/DMYV exam this trains for. See js/challenges.js, which layers
 * device validators onto a subset of these and turns the rest into
 * self-certified voice/procedure checklists.
 */
(function (global) {
  "use strict";
  global.CHALLENGES_RAW = [
    {
      number: 1,
      category: 'Geräteinbetriebnahme, System-Setup & Grundeinstellungen',
      title: 'Herstellen der grundlegenden Betriebsbereitschaft im Seefunkmodus',
      important: 'Das Gerät muss aus dem Ausschaltzustand in den betriebsbereiten Seefunkmodus versetzt werden.',
      steps: ['Hauptschalter oder EIN/AUS-Drehknopf betätigen.', 'Modus am Gerät überprüfen; falls ATIS aktiv ist, auf Seefunk/GMDSS umschalten.', 'Anruf- und Notkanal 16 anwählen.', 'High Power (25 W) auf dem Display verifizieren.', 'Lautstärke auf mittlere Hörstärke einstellen.', 'Rauschsperre (Squelch) öffnen, bis Rauschen ertönt, danach knapp bis zum Verstummen eindrehen.'],
      criteria: 'Modus Seefunk aktiv, Kanal 16 eingestellt, SQL an der Rauschgrenze, Sendeleistung 25 W im Display.',
    },
    {
      number: 2,
      category: 'Geräteinbetriebnahme, System-Setup & Grundeinstellungen',
      title: 'Kalibrierung der Rauschsperre (Squelch) bei Kanalwechsel',
      important: 'Das Signal darf bei Kanalwechsel nicht durch einen zu hoch eingestellten Squelch unterdrückt werden.',
      steps: ['Kanalwechsel von Kanal 16 auf einen Arbeitskanal (z. B. Kanal 72) durchführen.', 'Squelch-Regler vollständig öffnen, bis Dauerrauschen hörbar ist.', 'Lautstärke auf Angenehmheitswert regulieren.', 'Squelch-Regler langsam schließen, bis das Rauschen exakt erlischt.'],
      criteria: 'Rauschsperre ist präzise an der Wahrnehmungsgrenze des gewählten Arbeitskanals kalibriert.',
    },
    {
      number: 3,
      category: 'Geräteinbetriebnahme, System-Setup & Grundeinstellungen',
      title: 'Umstellung der Sendeleistung für Nahbereichs-Routineverkehr',
      important: 'Verhindern von Weitreichenstörungen durch Herabsetzung der Sendeleistung im Nahbereich.',
      steps: ['Einstellung auf Arbeitskanal (z. B. Kanal 69) prüfen.', 'Taste HI/LO beziehungsweise 1/25 W betätigen.', 'Anzeige im Display auf 1 W beziehungsweise LOW kontrollieren.'],
      criteria: 'Umschaltung auf 1 W Sendeleistung erfolgreich im Display visualisiert.',
    },
    {
      number: 4,
      category: 'Geräteinbetriebnahme, System-Setup & Grundeinstellungen',
      title: 'Manuelle Eingabe der Schiffsposition im DSC-Controller',
      important: 'Korrektur der Geokoordinaten bei fehlender automatischer GNSS-Einspeisung.',
      steps: ['Menüaufruf MENU -> DSC SETUP oder POS/TIME.', 'Eingabemaske für Breitengrad (Latitude) wählen.', 'Geokoordinaten (z. B. 54^\\circ 10\' N) eingeben.', 'Eingabemaske für Längengrad (Longitude) wählen.', 'Geokoordinaten (z. B. 011^\\circ 55\' E) eingeben.', 'Eingabe speichern (ENTER / SAVE).'],
      criteria: 'Exakte Übereinstimmung der im Display visualisierten Koordinaten mit den Prüfungs-Vorgabedaten.',
    },
    {
      number: 5,
      category: 'Geräteinbetriebnahme, System-Setup & Grundeinstellungen',
      title: 'Manuelle Aktualisierung der UTC-Uhrzeit im DSC-Controller',
      important: 'Zeitstempelgenaue Aussendung von DSC-Alarmen nach Weltzeit (UTC).',
      steps: ['Menüpunkt POS/TIME INJECTION anwählen.', 'Untermenü UTC TIME aufrufen.', 'Vorgegebene vierstellige UTC-Zeit (z. B. 1425) eingeben.', 'Eingabe bestätigen und Menü verlassen.'],
      criteria: 'Die eingegebene UTC-Zeit wird im Hauptbildschirm korrekt geführt.',
    },
    {
      number: 6,
      category: 'Geräteinbetriebnahme, System-Setup & Grundeinstellungen',
      title: 'Überprüfung des DSC-Wachempfängers auf Kanal 70',
      important: 'Der intern eingebaute DSC-Wachempfänger muss kontinuierlich auf Kanal 70 lauschen.',
      steps: ['Statusanzeige des Dual-Watch- bzw. GMDSS-Empfängers im Display prüfen.', 'Verifizieren, dass Kanal 70 nicht durch manuelle Einstellungen blockiert ist.'],
      criteria: 'Nachweis der aktiven Kanal-70-Bereitschaft im Gerätedisplay.',
    },
    {
      number: 7,
      category: 'Geräteinbetriebnahme, System-Setup & Grundeinstellungen',
      title: 'Systemabfrage der eigenen MMSI und des Rufzeichens',
      important: 'Identifikation der eigenen Funkstellenkennung vor Betriebsaufnahme.',
      steps: ['Menü RADIO INFO / MMSI SHOW ansteuern.', 'Neunstellige MMSI ablesen und mit Schiffspapieren abgleichen.', 'Rufzeichen (Call Sign) verifizieren.'],
      criteria: 'Korrekte Anzeige der hinterlegten MMSI im System.',
    },
    {
      number: 8,
      category: 'Geräteinbetriebnahme, System-Setup & Grundeinstellungen',
      title: 'Auswahllogik Simplex- vs. Duplex-Kanäle',
      important: 'Verständnis, dass Schiff-zu-Schiff-Kommunikation auf Duplex-Kanälen technisch unmöglich ist.',
      steps: ['Geforderten Arbeitskanal am Kanalwahlknopf wählen.', 'Im Display prüfen, ob DUPLEX oder SIMPLEX angezeigt wird.', 'Bei Schiff-zu-Schiff-Aufgaben auf einen Simplex-Kanal (z. B. 69, 72, 77) ausweichen.'],
      criteria: 'Richtige Kanalauswahl basierend auf der angesteuerten Gegenstelle.',
    },
    {
      number: 9,
      category: 'Geräteinbetriebnahme, System-Setup & Grundeinstellungen',
      title: 'Prüfen und Deaktivieren der Dual-Watch-Funktion',
      important: 'Vermeidung von ungewollten Kanalwechseln durch die Zwei-Kanal-Überwachung während einer Prüfungsaufgabe.',
      steps: ['Taste DW oder TRI betätigen, um den Mehrkanalbetrieb zu beenden.', 'Verifizieren, dass der Transceiver starr auf dem Arbeitskanal oder Kanal 16 steht.'],
      criteria: 'Reiner Einkanalbetrieb auf dem geforderten Zielkanal etabliert.',
    },
    {
      number: 10,
      category: 'Geräteinbetriebnahme, System-Setup & Grundeinstellungen',
      title: 'Zurücksetzen von vorangegangenen Alarmen im Speicher',
      important: 'Bereinigung des Systemzustands vor Beginn einer neuen Prüfungsaufgabe.',
      steps: ['Menü CALL LOG oder UNREAD MESSAGES aufrufen.', 'Vorhandene Nachrichten quittieren und löschen (CLEAR / DELETE).', 'Display in die Grundstellung (Kanal 16, Notbereitschaft) bringen.'],
      criteria: 'Controller zeigt keinen ungelesenen Speicherinhalt mehr an.',
    },
    {
      number: 11,
      category: 'Notverkehr – DSC-Notalarm und Sprechfunk-Notmeldung',
      title: 'Aussenden eines unbestimmten Notalarms (Undesignated Distress Alert)',
      important: 'Unmittelbare Auslösung des Notalarms bei extremer Zeitnot ohne Notgrundauswahl.',
      steps: ['Abdeckung der DISTRESS-Taste anheben.', 'DISTRESS-Taste ununterbrochen für mindestens 3 Sekunden gedrückt halten (optischer/akustischer Countdown).', 'Übertragung des Alarms im Display abwarten (DISTRESS ALERT SENT).', 'Automatischen Wechsel des Geräts auf Kanal 16 kontrollieren.'],
      criteria: 'Haltezeit eingehalten, Notalarm auf Kanal 70 gesendet, Transceiver schaltet selbsttätig empfangsbereit auf Kanal 16.',
    },
    {
      number: 12,
      category: 'Notverkehr – DSC-Notalarm und Sprechfunk-Notmeldung',
      title: 'Editieren und Senden eines Notalarms – Grund: Feuer/Explosion (Fire/Explosion)',
      important: 'Exakte Notgrundauswahl im DSC-Menü vor Auslösung.',
      steps: ['MENU -> DSC CALL -> DISTRESS MSG aufrufen.', 'Notgrund FIRE, EXPLOSION selektieren.', 'Gegebenenfalls Position und UTC-Zeit korrigieren.', 'DISTRESS-Taste 3 Sekunden gedrückt halten.', 'Nach Ausstrahlung Wechsel auf Kanal 16 verifizieren.'],
      criteria: 'DSC-Notalarm enthält das Attribut FIRE, EXPLOSION sowie gültige Position und Zeitstempel.',
    },
    {
      number: 13,
      category: 'Notverkehr – DSC-Notalarm und Sprechfunk-Notmeldung',
      title: 'Editieren und Senden eines Notalarms – Grund: Wassereinbruch (Flooding)',
      important: 'Programmierung der Alarmmeldung bei Wassereinbruch.',
      steps: ['Menü DISTRESS MSG öffnen.', 'Notgrund FLOODING wählen.', 'DISTRESS-Taste für 3 Sekunden auslösen.'],
      criteria: 'Notalarm mit Attribut FLOODING korrekt auf Kanal 70 übertragen.',
    },
    {
      number: 14,
      category: 'Notverkehr – DSC-Notalarm und Sprechfunk-Notmeldung',
      title: 'Editieren und Senden eines Notalarms – Grund: Kollision (Collision)',
      important: 'Standardisierte DSC-Editierung bei Schiffskollision.',
      steps: ['Notfallmenü anwählen.', 'Notgrund COLLISION selektieren.', 'Dreisekündige Auslösung über die DISTRESS-Taste durchführen.'],
      criteria: 'Notgrund COLLISION im gesendeten DSC-Datenpaket enthalten.',
    },
    {
      number: 15,
      category: 'Notverkehr – DSC-Notalarm und Sprechfunk-Notmeldung',
      title: 'Editieren und Senden eines Notalarms – Grund: Grundberührung (Grounding)',
      important: 'Alarmierung bei Festkommen auf Fels oder Sandbank.',
      steps: ['Notfallmenü im Controller öffnen.', 'Option GROUNDING wählen.', 'DISTRESS-Taste 3 Sekunden betätigen.'],
      criteria: 'Übertragung mit Parameter GROUNDING abgeschlossen.',
    },
    {
      number: 16,
      category: 'Notverkehr – DSC-Notalarm und Sprechfunk-Notmeldung',
      title: 'Editieren und Senden eines Notalarms – Grund: Kentern / Schlagseite (Listing/Capsizing)',
      important: 'Schnelle Menüauswahl bei drohender Kenterung.',
      steps: ['Notfallmenü im Controller öffnen.', 'Option LISTING, CAPSIZING markieren.', 'DISTRESS-Taste 3 Sekunden halten.'],
      criteria: 'Notalarm mit Attribut LISTING, CAPSIZING gesendet.',
    },
    {
      number: 17,
      category: 'Notverkehr – DSC-Notalarm und Sprechfunk-Notmeldung',
      title: 'Editieren und Senden eines Notalarms – Grund: Sinken (Sinking)',
      important: 'Voreinstellung bei unmittelbar drohendem Untergang.',
      steps: ['Menü DISTRESS CALL ansteuern.', 'Notgrund SINKING wählen.', 'DISTRESS-Taste 3 Sekunden gedrückt halten.'],
      criteria: 'Aussendung des Alarms mit Attribut SINKING im Display bestätigt.',
    },
    {
      number: 18,
      category: 'Notverkehr – DSC-Notalarm und Sprechfunk-Notmeldung',
      title: 'Editieren und Senden eines Notalarms – Grund: Man Overboard (MOB)',
      important: 'Auslösung bei Person über Bord.',
      steps: ['Notfallmenü öffnen.', 'Notgrund PERSON OVERBOARD / MAN OVERBOARD wählen.', 'DISTRESS-Taste 3 Sekunden lang betätigen.'],
      criteria: 'Notalarm mit Attribut MAN OVERBOARD gesendet.',
    },
    {
      number: 19,
      category: 'Notverkehr – DSC-Notalarm und Sprechfunk-Notmeldung',
      title: 'Editieren und Senden eines Notalarms – Grund: Treiben / Manövrierunfähigkeit (Disabled and Adrift)',
      important: 'Notfallkennzeichnung bei Manövrierunfähigkeit in gefahrenträchtiger Lage.',
      steps: ['Notfallmenü aufrufen.', 'Notgrund DISABLED AND ADRIFT selektieren.', 'DISTRESS-Taste 3 Sekunden drücken.'],
      criteria: 'DSC-Frame mit DISABLED AND ADRIFT übertragen.',
    },
    {
      number: 20,
      category: 'Notverkehr – DSC-Notalarm und Sprechfunk-Notmeldung',
      title: 'Editieren und Senden eines Notalarms – Grund: Schiff verlassen (Abandoning Vessel)',
      important: 'Alarmierung unmittelbar vor dem Übersteigen in Rettungsmittel.',
      steps: ['Menü DISTRESS MSG wählen.', 'Notgrund UNDESIGNATED oder ABANDONING SHIP markieren.', 'DISTRESS-Taste 3 Sekunden gedrückt halten.'],
      criteria: 'Notalarm vor Verlassen des Schiffs abgesendet.',
    },
    {
      number: 21,
      category: 'Notverkehr – DSC-Notalarm und Sprechfunk-Notmeldung',
      title: 'Sprechfunk-Notmeldung nach Notalarm (Szenario: Feuer im Motorraum)',
      important: 'Exakte Strukturierung der Notmeldung auf Kanal 16 im Sprechfunkverfahren.',
      steps: ['Nach dem DSC-Notalarm Verbleib auf Kanal 16 verifizieren.', 'Sendetaste (PTT) am Mikrofon drücken und halten.', 'Notanruf sprechen: MAYDAY (1x).', 'Schiffsname (3x), THIS IS (1x), Schiffsname (1x), Rufzeichen (1x), MMSI (1x).', 'Notmeldung abgeben:', 'MAYDAY (1x)', 'Schiffsname (1x), Rufzeichen (1x)', 'Position: IN POSITION 54 DEGREES 12 MINUTES NORTH, 011 DEGREES 50 MINUTES EAST', 'Notfallart & Hilfeleistung: FIRE IN ENGINE ROOM, REQUIRE IMMEDIATE ASSISTANCE', 'Ergänzende Angaben: 4 PERSONS ON BOARD, PREPARING LIFERAFT', 'Sprechaufforderung: OVER', 'PTT-Taste loslassen.'],
      criteria: 'Lückenlose, phonetisch korrekte Abgabe der Notmeldung ohne Notizen, Abschluss mit OVER.',
    },
    {
      number: 22,
      category: 'Notverkehr – DSC-Notalarm und Sprechfunk-Notmeldung',
      title: 'Sprechfunk-Notmeldung nach Notalarm (Szenario: Wassereinbruch im Maschinenraum)',
      important: 'Präzise Übermittlung der Notlage Wassereinbruch.',
      steps: ['Kanal 16 verifizieren.', 'PTT drücken.', 'Notanruf: MAYDAY - Schiffsname (3x) - THIS IS - Schiffsname (1x) - Rufzeichen (1x) - MMSI (1x).', 'Notmeldung: MAYDAY - Schiffsname - IN POSITION... - UNCONTROLLED FLOODING IN ENGINE ROOM, REQUIRE IMMEDIATE ASSISTANCE - 3 PERSONS ON BOARD - OVER.', 'PTT loslassen.'],
      criteria: 'Phonetisch einwandfreie Aussprache aller Kerndaten, Stopp nach OVER.',
    },
    {
      number: 23,
      category: 'Notverkehr – DSC-Notalarm und Sprechfunk-Notmeldung',
      title: 'Sprechfunk-Notmeldung nach Notalarm (Szenario: Kollision mit Frachtschiff)',
      important: 'Übermittlung des Havariegrundes Collision.',
      steps: ['Kanal 16 verifizieren.', 'PTT betätigen.', 'Notanruf & Notmeldung: MAYDAY ... COLLISION WITH CARGO VESSEL, TAKING WATER, REQUIRE IMMEDIATE ASSISTANCE ... 5 PERSONS ON BOARD - OVER.'],
      criteria: 'Vollständige Einhaltung des internationalen Funkschemas.',
    },
    {
      number: 24,
      category: 'Notverkehr – DSC-Notalarm und Sprechfunk-Notmeldung',
      title: 'Sprechfunk-Notmeldung nach Notalarm (Szenario: Grundberührung mit Wassereinbruch)',
      important: 'Kombination aus Grundberührung und Leckage übermitteln.',
      steps: ['Kanal 16 verifizieren.', 'PTT drücken.', 'MAYDAY ... GROUNDED ON ROCK, HEAVY LEAKAGE, REQUIRE IMMEDIATE ASSISTANCE ... OVER.'],
      criteria: 'Exakte Angaben zu Position und Hilfebedarf.',
    },
    {
      number: 25,
      category: 'Notverkehr – DSC-Notalarm und Sprechfunk-Notmeldung',
      title: 'Sprechfunk-Notmeldung nach Notalarm (Szenario: Mensch über Bord bei Nacht)',
      important: 'MOB-Notfallmeldung zur Auslösung von Seenotrettungsmaßnahmen.',
      steps: ['Kanal 16 kontrollieren.', 'PTT betätigen.', 'MAYDAY ... PERSON OVERBOARD IN POSITION ... AT 2200 UTC, REQUIRE IMMEDIATE ASSISTANCE ... OVER.'],
      criteria: 'Zeitstempel und Position des Vorfalls im Sprechfunk übermittelt.',
    },
    {
      number: 26,
      category: 'Notverkehr – DSC-Notalarm und Sprechfunk-Notmeldung',
      title: 'Sprechfunk-Notmeldung nach Notalarm (Szenario: Treiben auf Untiefe in rauer See)',
      important: 'Schilderung der Gefährdung durch Abtrift.',
      steps: ['Kanal 16 verifizieren.', 'PTT drücken.', 'MAYDAY ... ENGINE FAILURE, DRIFTING IN ROUGH SEA TOWARDS SHALLOW WATER, REQUIRE IMMEDIATE ASSISTANCE ... OVER.'],
      criteria: 'Gefahrenlage im Sprechfunk präzise dargestellt.',
    },
    {
      number: 27,
      category: 'Notverkehr – DSC-Notalarm und Sprechfunk-Notmeldung',
      title: 'Sprechfunk-Notmeldung ohne vorherigen DSC-Notalarm',
      important: 'Abgabe der Notmeldung rein per Sprechfunk bei defektem DSC-Controller.',
      steps: ['Transceiver direkt auf Kanal 16 einstellen.', 'Sendeleistung 25 W kontrollieren.', 'Notanruf und Notmeldung unmittelbar per Sprechfunk ausgeben.'],
      criteria: 'Beginn mit MAYDAY ohne vorangegangene DSC-Aktivierung.',
    },
    {
      number: 28,
      category: 'Notverkehr – DSC-Notalarm und Sprechfunk-Notmeldung',
      title: 'Sprechfunk-Notmeldung bei relativer Positionsangabe',
      important: 'Formulierung einer relativen Positionsbeschreibung zu einem Peilobjekt, falls keine Koordinaten vorliegen.',
      steps: ['Kanal 16 wählen.', 'PTT drücken.', 'Notmeldung sprechen: POSITION 5 NAUTICAL MILES SOUTH OF CAPE ARKONA.'],
      criteria: 'Peilung, Distanz und Bezugspunkt regelkonform genannt.',
    },
    {
      number: 29,
      category: 'Notverkehr – DSC-Notalarm und Sprechfunk-Notmeldung',
      title: 'Wiederholung einer Notmeldung bei Ausbleiben von Empfangsbestätigungen',
      important: 'Taktische Wiederholung der Notmeldung nach Verstreichen einer Wartefrist.',
      steps: ['Auf Kanal 16 für 3 bis 4 Minuten nach dem ersten Notruf lauschen.', 'Bei Ausbleiben einer Antwort Notmeldung auf Kanal 16 identisch wiederholen.'],
      criteria: 'Fristgerechte Wiederholung der vollständigen Notmeldung.',
    },
    {
      number: 30,
      category: 'Notverkehr – DSC-Notalarm und Sprechfunk-Notmeldung',
      title: 'Sprechfunk-Notmeldung mit detaillierter Verletzten- und Personenanzahl',
      important: 'Präzisierung der Personenstärke an Bord für Seenotrettungseinheiten.',
      steps: ['Kanal 16 einstellen.', 'PTT drücken.', 'Notmeldung sprechen: ... 6 PERSONS ON BOARD, TWO PERSONS SEVERE BURNS, REQUIRE IMMEDIATE MEDICAL AND RESCUE ASSISTANCE - OVER.'],
      criteria: 'Medizinische Notlage korrekt in die Notmeldung integriert.',
    },
    {
      number: 31,
      category: 'Notverkehr – Empfang, Bestätigung, Hilfeleistung & Distress Relay',
      title: 'Speicherabfrage eines empfangenen DSC-Notalarms',
      important: 'Auslesen und Notieren der Notrufdaten aus dem DSC-Empfangsspeicher.',
      steps: ['DSC-Alarmton am Gerät quittieren (SILENCE / CLEAR).', 'Menü DSC LOG -> RECEIVED CALLS -> DISTRESS LOG aufrufen.', 'Relevante Daten auslesen: MMSI des Havaristen, Notgrund, Geokoordinaten, UTC-Zeitstempel.'],
      criteria: 'Auslesen der Vierer-Datengruppe (MMSI, Grund, Position, Zeit) aus dem Speicher.',
    },
    {
      number: 32,
      category: 'Notverkehr – Empfang, Bestätigung, Hilfeleistung & Distress Relay',
      title: 'Validierung des DSC-Bestätigungsverbots für Seefunkstellen',
      important: 'Das strikte Verbot für Schiffsfunkstellen beachten, einen DSC-Notalarm per DSC zu bestätigen.',
      steps: ['Empfang des DSC-Notalarms am Gerät feststellen.', 'Keinesfalls eine DSC-Acknowledge-Funktion betätigen.', 'Auf Kanal 16 umschalten und Sprechfunk der Küstenfunkstelle abwarten.'],
      criteria: 'Keine manuelle Auslösung einer DSC-Empfangsbestätigung durch den Bediener.',
    },
    {
      number: 33,
      category: 'Notverkehr – Empfang, Bestätigung, Hilfeleistung & Distress Relay',
      title: 'Sprechfunk-Empfangsbestätigung eines Notalarms auf Kanal 16',
      important: 'Bestätigung einer Notmeldung per Sprechfunk auf Kanal 16, wenn keine Küstenfunkstelle antwortet und das eigene Schiff Hilfe leisten kann.',
      steps: ['Warten, ob eine Küstenfunkstelle auf Kanal 16 antwortet.', 'Falls keine Antwort erfolgt: PTT drücken.', 'Bestätigungsanruf tätigen:', 'MAYDAY', 'Schiffsname/Rufzeichen/MMSI des Havaristen (3x)', 'THIS IS', 'Eigener Schiffsname (3x), Rufzeichen (1x)', 'RECEIVED MAYDAY', 'OVER'],
      criteria: 'Korrekte Anwendung des Schlüsselbegriffs RECEIVED MAYDAY im Sprechfunk.',
    },
    {
      number: 34,
      category: 'Notverkehr – Empfang, Bestätigung, Hilfeleistung & Distress Relay',
      title: 'Hilfeleistungsangebot mit Positions- und Ankunftszeitangabe (ETA)',
      important: 'Übermittlung der eigenen Anfahrtsdaten an den Havaristen im Notverkehr.',
      steps: ['Kanal 16 verifizieren.', 'PTT drücken.', 'Sprechfunkmeldung abgeben:', 'MAYDAY - Schiffsname Havarist - THIS IS - Eigener Schiffsname / Rufzeichen', 'RECEIVED MAYDAY', 'MY POSITION IS ...', 'PROCEEDING AT 10 KNOTS TO YOUR POSITION, ETA 1430 UTC', 'OVER'],
      criteria: 'Positions- und ETA-Angabe regelkonform im Sprechfunk übermittelt.',
    },
    {
      number: 35,
      category: 'Notverkehr – Empfang, Bestätigung, Hilfeleistung & Distress Relay',
      title: 'Empfangsbestätigung bei unmittelbarer Nähe zum Havaristen',
      important: 'Sofortige Bestätigung per Sprechfunk bei Sichtkontakt zum Havaristen.',
      steps: ['Kanal 16 wählen.', 'PTT drücken.', 'MAYDAY - Name Havarist - THIS IS - Eigener Name - RECEIVED MAYDAY, I AM IN SIGHT OF YOU, STANDING BY TO TAKE OFF SURVIVORS - OVER.'],
      criteria: 'Unverzügliche Sprechfunkbestätigung bei Sichtkontakt durchgeführt.',
    },
    {
      number: 36,
      category: 'Notverkehr – Empfang, Bestätigung, Hilfeleistung & Distress Relay',
      title: 'Weiterleitung eines Notalarms (Mayday Relay) an eine Küstenfunkstelle',
      important: 'Not-Weiterleitung per Sprechfunk an ein MRCC, wenn ein Havarist seinen Notruf nicht selbst aussenden kann.',
      steps: ['Kanal 16 einstellen.', 'PTT drücken.', 'Anruf: MAYDAY RELAY (3x).', 'Adressat: BREMEN RESCUE (3x) oder ALL STATIONS (3x).', 'Absender: THIS IS - Eigener Schiffsname (3x), Rufzeichen (1x), MMSI (1x).', 'Text: MAYDAY - Schiffsname Havarist / Rufzeichen - Position Havarist - Notlage - OVER.'],
      criteria: 'Dreifache Verwendung von MAYDAY RELAY, fehlerfreie Wiedergabe der fremden Notfalldaten.',
    },
    {
      number: 37,
      category: 'Notverkehr – Empfang, Bestätigung, Hilfeleistung & Distress Relay',
      title: 'Mayday Relay an ALL STATIONS nach Sichten eines gekenterten Rettungsfloßes',
      important: 'Weiterleitung einer Notbeobachtung ohne direkten Funkkontakt zum Havaristen.',
      steps: ['Kanal 16 verifizieren.', 'PTT betätigen.', 'MAYDAY RELAY (3x) - ALL STATIONS (3x) - THIS IS - Eigener Name (3x) / Rufzeichen.', 'IN POSITION NEAR LIGHT BUOY HUMBER 5 CAPSIZED LIFERAFT OBSERVED, NO SURVIVORS SIGHTED, SHIPS IN AREA KEPT TO LOOKOUT - OVER.'],
      criteria: 'Phonetisch einwandfreie Wiedergabe der amtlichen Seefunktext-Inhalte.',
    },
    {
      number: 38,
      category: 'Notverkehr – Empfang, Bestätigung, Hilfeleistung & Distress Relay',
      title: 'Mayday Relay per Sprechfunk nach ungeklärter DSC-Notmeldung eines Dritten',
      important: 'Weiterleiten eines empfangenen DSC-Notalarms per Sprechfunk, wenn dieser von keiner Küstenfunkstelle bestätigt wurde.',
      steps: ['DSC-Speicher aufrufen und Daten des fremden Notalarms notieren.', 'Auf Kanal 16 umschalten.', 'PTT drücken: MAYDAY RELAY (3x) - ALL STATIONS (3x) - THIS IS - Eigener Name (3x).', 'Text der gelesenen Notmeldung übermitteln (MMSI des fremden Schiffs, Position, Zeit).', 'Mit OVER abschließen.'],
      criteria: 'Fehlerfreie Übertragung der aus dem DSC-Log ausgelesenen Kennungen.',
    },
    {
      number: 39,
      category: 'Notverkehr – Empfang, Bestätigung, Hilfeleistung & Distress Relay',
      title: 'Übernahme der Notverkehrs-Koordination bei Schweigen der Küstenfunkstelle',
      important: 'Führung des Notverkehrs durch das erste helfende Schiff vor Ort.',
      steps: ['Auf Kanal 16 den Funkverkehr strukturieren.', 'Notmeldungen empfangen und Suchmuster mit beteiligten Einheiten koordinieren.'],
      criteria: 'Professionelle Führung des Sprechfunkverkehrs im Notfall.',
    },
    {
      number: 40,
      category: 'Notverkehr – Empfang, Bestätigung, Hilfeleistung & Distress Relay',
      title: 'Funkverkehr vor Ort (On-Scene Communications) mit SAR-Helikopter',
      important: 'Abstimmung von Rettungsmanövern auf dem Not- oder Arbeitskanal.',
      steps: ['Funkbereitschaft auf Kanal 16 oder zugewiesenem Arbeitskanal herstellen.', 'PTT drücken: RESCUE HELICOPTER 15 - THIS IS - Eigener Schiffsname.', 'Windrichtung, Kurs, Fahrt und Decksvorbereitungen durchgeben.'],
      criteria: 'Präzise, knappe Sprechfunk-Kommunikation für die Winch-Operation.',
    },
    {
      number: 41,
      category: 'Notverkehr – Empfang, Bestätigung, Hilfeleistung & Distress Relay',
      title: 'Empfangsbestätigung eines Not-Relais einer Küstenfunkstelle',
      important: 'Quittierung einer von einer Küstenfunkstelle verbreiteten Notmeldung.',
      steps: ['Kanal 16 lauschen.', 'PTT drücken.', 'Küstenfunkstelle ansprechen, Empfang des MAYDAY RELAY bestätigen und eigene Position/Bereitschaft zur Ausschau mitteilen.'],
      criteria: 'Ordnungsgemäße Bestätigung an das MRCC.',
    },
    {
      number: 42,
      category: 'Notverkehr – Empfang, Bestätigung, Hilfeleistung & Distress Relay',
      title: 'Abwicklung von Sprechfunkübertragungen während einer aktiven SAR-Suche',
      important: 'Minimierung des Funkverkehrs zur Reinerhaltung des Notkanals.',
      steps: ['Nur bei Sichtung von Trümmern, Rettungsmitteln oder Personen PTT betätigen.', 'Meldung kurz und präzise abgeben.'],
      criteria: 'Strikte Funkdisziplin gewahrt.',
    },
    {
      number: 43,
      category: 'Notverkehr – Empfang, Bestätigung, Hilfeleistung & Distress Relay',
      title: 'Weiterleitung eines Notalarms bei Ausfall der eigenen DSC-Einheit',
      important: 'Nutzung des reinen Sprechfunks zur Abgabe einer Relais-Meldung.',
      steps: ['Kanal 16 direkt anwählen.', 'MAYDAY RELAY-Prozedur wie unter Frage 36 abarbeiten.'],
      criteria: 'Vollständiger Ablauf ohne DSC-Nutzung.',
    },
    {
      number: 44,
      category: 'Notverkehr – Empfang, Bestätigung, Hilfeleistung & Distress Relay',
      title: 'Quittierung und Weiterverarbeitung von eingehenden Mayday-Relay-Sprüchen',
      important: 'Auswertung, ob das eigene Schiff nahe genug ist, um an der Suche mitzuwirken.',
      steps: ['Nachrichteninhalt notieren.', 'Eigene Position mit Havarieposition vergleichen.', 'Bei Eignung Küstenfunkstelle per Sprechfunk verständigen.'],
      criteria: 'Korrekte Lagebeurteilung und operative Reaktion.',
    },
    {
      number: 45,
      category: 'Notverkehr – Empfang, Bestätigung, Hilfeleistung & Distress Relay',
      title: 'Funkabwicklung nach Rettung aller Personen durch ein drittes Schiff',
      important: 'Information der den Notverkehr leitenden Stelle über die erfolgreiche Bergung.',
      steps: ['Kanal 16 wählen.', 'PTT drücken: Notverkehrsleiter anfunken und Vollzug der Rettung melden.'],
      criteria: 'Klarstellung des aktuellen Rettungsstatus über Sprechfunk.',
    },
    {
      number: 46,
      category: 'Funkstille (Silence Mayday) & Beendigung des Notverkehrs (Silence Fini)',
      title: 'Aufforderung zur Funkstille durch den Notverkehrsleiter (Silence Mayday)',
      important: 'Durchsetzung absoluter Notfunkstille bei Störungen durch unberechtigte Funkstellen.',
      steps: ['Auf Kanal 16 feststellen, dass eine fremde Funkstelle den Notverkehr stört.', 'PTT drücken.', 'Störende Funkstelle ansprechen oder ALL STATIONS wählen.', 'THIS IS - Eigener Schiffsname (3x) (Notverkehrsleiter).', 'Befehl aussprechen: SILENCE MAYDAY.', 'Mit OUT abschließen.'],
      criteria: 'Exakte Verwendung der Phrasierung SILENCE MAYDAY durch das leitende Fahrzeug.',
    },
    {
      number: 47,
      category: 'Funkstille (Silence Mayday) & Beendigung des Notverkehrs (Silence Fini)',
      title: 'Aufforderung zur Funkstille durch ein nicht-leitendes Schiff (Silence Distress)',
      important: 'Gebieten von Funkstille durch eine Schiffsfunkstelle, die nicht die Einsatzleitung hat.',
      steps: ['Kanal 16 verifizieren.', 'PTT drücken.', 'Störendes Schiff anrufen: [NAME STÖRENDES SCHIFF] - THIS IS - [EIGENER NAME].', 'Befehl aussprechen: SILENCE DISTRESS.', 'Mit OUT beenden.'],
      criteria: 'Korrekte Unterscheidung zwischen SILENCE MAYDAY (Leitung) und SILENCE DISTRESS (Nicht-Leitung).',
    },
    {
      number: 48,
      category: 'Funkstille (Silence Mayday) & Beendigung des Notverkehrs (Silence Fini)',
      title: 'Beendigung des Notverkehrs per Sprechfunk (Silence Fini) durch Küstenfunkstelle',
      important: 'Aufhebung der Funkstille nach Beendigung des Seenotfalls.',
      steps: ['Auf Kanal 16 den Aufhebungsspruch der Leitstelle abwarten.', 'Schema aufnehmen: MAYDAY - ALL STATIONS (3x) - THIS IS - Name der Leitstelle - TIME... - Name Havarist - SILENCE FINI.', 'Das Verstehen des Formats nachweisen.'],
      criteria: 'Identifikation des Schlüsselbegriffs SILENCE FINI als Beendigung der Notfunkstille.',
    },
    {
      number: 49,
      category: 'Funkstille (Silence Mayday) & Beendigung des Notverkehrs (Silence Fini)',
      title: 'Beendigung des Notverkehrs per Sprechfunk durch den ehemaligen Havaristen',
      important: 'Abgabe der Entwarnung nach Wiederherstellung der eigenen Sicherheit.',
      steps: ['Kanal 16 wählen.', 'PTT drücken.', 'MAYDAY - ALL STATIONS (3x) - THIS IS - Eigener Schiffsname (3x) / Rufzeichen / MMSI.', '1510 UTC YACHT FREYBURG RESCUED, ENGINE RUNNING AGAIN, NOT IN DISTRESS ANYMORE.', 'SILENCE FINI - OUT.'],
      criteria: 'Einwandfreie Strukturierung der Notverkehrsbeendigung.',
    },
    {
      number: 50,
      category: 'Funkstille (Silence Mayday) & Beendigung des Notverkehrs (Silence Fini)',
      title: 'Wiederaufnahme des normalen Seefunkdienstes nach Silence Fini',
      important: 'Systemzustand des Funkgeräts nach Aufhebung des Notverkehrs rekonfigurieren.',
      steps: ['Kanal 16 auf Hörbereitschaft belassen.', 'Rauschsperre und Lautstärke prüfen.', 'Schiffstagebuch-Eintrag vornehmen.'],
      criteria: 'Rückkehr zum Normalbetrieb regelkonform ausgeführt.',
    },
    {
      number: 51,
      category: 'Funkstille (Silence Mayday) & Beendigung des Notverkehrs (Silence Fini)',
      title: 'Abweisen von unberechtigtem Routineverkehr während Notfunkstille',
      important: 'Konsequentes Verweigern von Antworten auf Routineanrufe während Notfunkstille aktiv ist.',
      steps: ['Routineanruf auf Kanal 16 während Notverkehr wahrnehmen.', 'Keinesfalls antworten oder auf Arbeitskanal wechseln.', 'Gegebenenfalls SILENCE DISTRESS aussenden.'],
      criteria: 'Absolute Reinerhaltung der Notfrequenz.',
    },
    {
      number: 52,
      category: 'Funkstille (Silence Mayday) & Beendigung des Notverkehrs (Silence Fini)',
      title: 'Verhängung partieller Funkstille bei Notfallmaßnahmen',
      important: 'Einschränkung des Funkverkehrs auf bestimmte Arbeitskanäle bei SAR-Einsätzen.',
      steps: ['Arbeitskanal (z. B. Kanal 67 oder 06) wählen.', 'PTT drücken: SILENCE DISTRESS aussenden.'],
      criteria: 'Funkstille auf dem spezifizierten Kanal etabliert.',
    },
    {
      number: 53,
      category: 'Funkstille (Silence Mayday) & Beendigung des Notverkehrs (Silence Fini)',
      title: 'Entwarnung per Sprechfunk nach Fehlauslösung von Silence Mayday',
      important: 'Unverzügliches Aufheben fälschlich verhängter Funkstille.',
      steps: ['Kanal 16 anwählen.', 'PTT drücken: Korrekturmeldung senden und Aufhebung bekanntgeben.'],
      criteria: 'Störung des VHF-Verkehrs unverzüglich geheilt.',
    },
    {
      number: 54,
      category: 'Funkstille (Silence Mayday) & Beendigung des Notverkehrs (Silence Fini)',
      title: 'Dokumentation der Notverkehrsbeendigung im Schiffstagebuch',
      important: 'Erfassung des Endes des Notverkehrs.',
      steps: ['UTC-Zeitpunkt von SILENCE FINI notieren.', 'Eintrag im Logbuch mit Funkprotokoll abgleichen.'],
      criteria: 'Vollständige protokollarische Nachbereitung.',
    },
    {
      number: 55,
      category: 'Funkstille (Silence Mayday) & Beendigung des Notverkehrs (Silence Fini)',
      title: 'Rekalibrierung der DSC-Bereitschaft nach Aufhebung der Notlage',
      important: 'Rückstellung aller temporären Alarmstromeinstellungen am DSC-Controller.',
      steps: ['DSC-Menü öffnen.', 'Alarm-Historie sichern/löschen.', 'Standard-Display-Ansicht aktivieren.'],
      criteria: 'Controller befindet sich im sauberen Standby-Status.',
    },
    {
      number: 56,
      category: 'Aufhebung von Fehlalarmen (Distress Cancel)',
      title: 'Unbeabsichtigtes Auslösen eines DSC-Notalarms – Sofortiges Stornieren am Gerät',
      important: 'Prozedural exakter Abbruch einer fehlerhaften DSC-Distress-Aussendung vor oder unmittelbar nach dem Senden.',
      steps: ['Bei unbeabsichtigtem Drücken sofort die Taste CANCEL am DSC-Controller betätigen.', 'Sollte der Alarm bereits auf Kanal 70 herausgegangen sein: Befehl CANCEL DISTRESS ALERT auf dem Display mit ENTER bestätigen.', 'Der Controller schaltet automatisch auf Kanal 16.'],
      criteria: 'DSC-Stornierung am Gerät ordnungsgemäß eingeleitet.',
    },
    {
      number: 57,
      category: 'Aufhebung von Fehlalarmen (Distress Cancel)',
      title: 'Entwarnungsmeldung per Sprechfunk auf Kanal 16 nach DSC-Fehlalarm',
      important: 'Verpflichtende Aussendung der Sprechfunk-Annullierung an ALL STATIONS nach jedem DSC-Fehlalarm.',
      steps: ['Kanal 16 kontrollieren.', 'PTT drücken.', 'Anrufgruppe: ALL STATIONS (3x).', 'Absender: THIS IS - Eigener Schiffsname (3x), Rufzeichen (1x), MMSI (1x).', 'Text: PLEASE CANCEL MY DISTRESS ALERT SENT AT 1245 UTC ON CHANNEL 70.', 'Identifikation: Schiffsname (1x), Rufzeichen (1x), MMSI (1x), UTC-Zeitstempel.', 'Abschluss: OUT.'],
      criteria: 'Vollständige Sprechfunk-Entwarnung ohne Verschweigen von MMSI oder Zeit; Abschluss mit OUT.',
    },
    {
      number: 58,
      category: 'Aufhebung von Fehlalarmen (Distress Cancel)',
      title: 'Fehlalarm-Aufhebung bei manueller Fehleingabe von Geokoordinaten',
      important: 'Entwarnung, wenn ein Notalarm mit falschen Positionsdaten versehentlich abgesendet wurde.',
      steps: ['DSC-Reset durchführen.', 'Auf Kanal 16 Entwarnung senden.', 'Korrekte Position im Freitext der Sprechfunk-Entwarnung nennen zur Verwirrungsvermeidung.'],
      criteria: 'Falschpositionierung im Sprechfunk-Cancel berichtigt.',
    },
    {
      number: 59,
      category: 'Aufhebung von Fehlalarmen (Distress Cancel)',
      title: 'Direkte Entwarnung an die Küstenfunkstelle nach Fehlauslösung',
      important: 'Gezielte Kontaktaufnahme mit dem MRCC zur Entwarnung bei direkter Erreichbarkeit.',
      steps: ['Kanal 16 wählen.', 'PTT drücken.', 'BREMEN RESCUE - THIS IS - Eigener Name / MMSI - CANCEL MY DISTRESS ALERT OF 0915 UTC - FALSE ALERT DUE TO OPERATOR ERROR - OUT.'],
      criteria: 'Küstenfunkstelle über Bedienerfehler informiert.',
    },
    {
      number: 60,
      category: 'Aufhebung von Fehlalarmen (Distress Cancel)',
      title: 'Abbruch eines versehentlich gestarteten DSC-Selbsttests (Distress Test)',
      important: 'Verhindern, dass ein Testmodus in einen realen Notalarm übergeht.',
      steps: ['Displayanzeige TEST CALL kontrollieren.', 'Bei Abweichung Taste CLEAR/STOP betätigen.'],
      criteria: 'Kein Ausstrahlen eines scharfen Notalarms auf Kanal 70.',
    },
    {
      number: 61,
      category: 'Aufhebung von Fehlalarmen (Distress Cancel)',
      title: 'Stornierung bei Halten der Distress-Taste unter 3 Sekunden',
      important: 'Verstehen des Sicherheits-Timers der Hardware-Taste.',
      steps: ['Taste DISTRESS vor Ablauf von 3 Sekunden loslassen.', 'Prüfen, ob der Countdown abbricht.', 'Hauptbildschirm verifizieren.'],
      criteria: 'Kein Alarm gesendet; keine Entwarnung auf Kanal 16 erforderlich.',
    },
    {
      number: 62,
      category: 'Aufhebung von Fehlalarmen (Distress Cancel)',
      title: 'Wiederholung einer unvollständigen Sprechfunk-Entwarnung',
      important: 'Korrektur, falls bei der ersten Entwarnung die MMSI vergessen wurde.',
      steps: ['PTT erneut betätigen.', 'ALL STATIONS ... CORRECTION: MY DISTRESS ALERT SENT AT 1000 UTC WITH MMSI 211234567 IS CANCELLED - OUT.'],
      criteria: 'Nachträgliche Vervollständigung aller Pflichtparameter.',
    },
    {
      number: 63,
      category: 'Aufhebung von Fehlalarmen (Distress Cancel)',
      title: 'Aufhebung eines Notalarms einer Handfunkanlage (VHF Portable)',
      important: 'Entwarnungsprozess für mobile VHF-DSC-Geräte an Bord.',
      steps: ['Gerätestornierung am Handfunkgerät vornehmen.', 'Entwarnungsmeldung über Hauptanlage oder Handfunkgerät auf Kanal 16 abgeben.'],
      criteria: 'Fehlalarm der Zweitanlage regelkonform annulliert.',
    },
    {
      number: 64,
      category: 'Aufhebung von Fehlalarmen (Distress Cancel)',
      title: 'Stornierung bei technischen Fehlfunktionen des Transceivers',
      important: 'Handhabung von Dauer-Transmit-Zuständen durch Hardwarefehler.',
      steps: ['Stromversorgung des Funkgeräts unterbrechen (Hard Reset).', 'Nach Neustart sofort Kanal 16 anwählen.', 'Sprechfunk-Entwarnung wegen technischer Störung abgeben.'],
      criteria: 'Wiederherstellung der Funkordnung auf Kanal 16.',
    },
    {
      number: 65,
      category: 'Aufhebung von Fehlalarmen (Distress Cancel)',
      title: 'Dokumentation der Fehlalarm-Stornierung im Schiffstagebuch',
      important: 'Nachweis der Entwarnung gegenüber Schifffahrtsbehörden.',
      steps: ['Uhrzeit des Fehlalarms und der Entwarnung protokollieren.', 'Ursache (Bedienfehler/Technik) vermerken.'],
      criteria: 'Vollständige Dokumentation ausgeführt.',
    },
    {
      number: 66,
      category: 'Dringlichkeitsverkehr (Urgency - PAN PAN)',
      title: 'Editieren und Senden eines DSC-Dringlichkeitsanrufs (Urgency All Ships)',
      important: 'Digitaler Ankündigungsruf einer Dringlichkeitsmeldung auf Kanal 70 an alle Funkstellen.',
      steps: ['MENU -> DSC CALL -> ALL SHIPS wählen.', 'Priorität URGENCY anwählen.', 'Arbeitskanal für das nachfolgende Gespräch im Controller hinterlegen.', 'DSC-Ruf auf Kanal 70 absenden.', 'Auf Kanal 16 schalten bzw. Umschaltung verifizieren.'],
      criteria: 'DSC-Anruf mit Priorität URGENCY erfolgreich an ALL SHIPS übermittelt.',
    },
    {
      number: 67,
      category: 'Dringlichkeitsverkehr (Urgency - PAN PAN)',
      title: 'Absetzen einer Sprechfunk-Dringlichkeitsmeldung auf Kanal 16 (Szenario: Ruderbruch)',
      important: 'Abgabe der Dringlichkeitsmeldung nach dem DSC-Anruf zur Warnung der Schifffahrt.',
      steps: ['Sendeleistung 25 W auf Kanal 16 verifizieren.', 'PTT drücken.', 'Dringlichkeitszeichen: PAN PAN (3x).', 'Adressat: ALL STATIONS (3x).', 'Absender: THIS IS - Eigener Schiffsname (3x), Rufzeichen (1x), MMSI (1x).', 'Position: Geokoordinaten oder relative Lage.', 'Sachverhalt: RUDDER BROKEN, DRIFTING IN ROUGH SEA TOWARDS SHALLOWS, REQUIRE TUG ASSISTANCE.', 'Sprechaufforderung: OVER.'],
      criteria: 'Dreifaches PAN PAN, deutliche Beschreibung des Assistenzbedarfs, Abschluss mit OVER.',
    },
    {
      number: 68,
      category: 'Dringlichkeitsverkehr (Urgency - PAN PAN)',
      title: 'Dringlichkeitsmeldung per Sprechfunk (Szenario: Entmastung ohne akute Sinkegefahr)',
      important: 'Richtige Wahl der Priorität Urgency bei Sachschaden ohne direkte Lebensgefahr.',
      steps: ['Kanal 16 wählen.', 'PTT drücken.', 'PAN PAN (3x) - ALL STATIONS (3x) - THIS IS - Name (3x) / Rufzeichen.', 'MAST BROKEN, RIGGING IN WATER, DANGER TO NAVIGATION, IN POSITION ... - OVER.'],
      criteria: 'Abgrenzung zum Notfall (MAYDAY) korrekt eingehalten.',
    },
    {
      number: 69,
      category: 'Dringlichkeitsverkehr (Urgency - PAN PAN)',
      title: 'DSC-Dringlichkeitsanruf an eine spezifische Küstenfunkstelle (Medico Call)',
      important: 'Einholung medizinischen Rats per Einzelanruf (Individual Call) mit Priorität Urgency.',
      steps: ['MENU -> INDIVIDUAL CALL.', 'MMSI der Küstenfunkstelle (z. B. 002111230 für Bremen Rescue) eingeben.', 'Priorität URGENCY wählen.', 'Ruf senden.'],
      criteria: 'Gezielter Einzelruf mit Priorität Urgency an die Rettungsleitstelle.',
    },
    {
      number: 70,
      category: 'Dringlichkeitsverkehr (Urgency - PAN PAN)',
      title: 'Absetzen einer Medico-Sprechfunkmeldung auf einem Arbeitskanal',
      important: 'Abwickeln des Funkverkehrs zur medizinischen Beratung auf dem zugewiesenen Kanal.',
      steps: ['Nach Bestätigung durch die Küstenfunkstelle auf den vereinbarten Arbeitskanal schalten.', 'PTT drücken.', 'PAN PAN - BREMEN RESCUE - THIS IS - Eigener Name.', 'REQUIRE MEDICAL ADVICE, CREW MEMBER WITH SUSPECTED FRACTURE OF ARM - OVER.'],
      criteria: 'Richtiger Kanalwechsel und korrekte Schilderung des Krankheitsbildes.',
    },
    {
      number: 71,
      category: 'Dringlichkeitsverkehr (Urgency - PAN PAN)',
      title: 'Dringlichkeitsmeldung wegen Treibgut / Gefährdung der Schifffahrt',
      important: 'Warnung anderer Verkehrsteilnehmer vor kollisionsgefährdeten Objekten.',
      steps: ['DSC-Anruf URGENCY an ALL SHIPS.', 'Sprechfunk auf Kanal 16: PAN PAN (3x) - ALL STATIONS (3x) ... SEMI-SUBMERGED CONTAINER DRIFTING IN POSITION ... - OVER.'],
      criteria: 'Gefahrenstelle präzise übermittelt.',
    },
    {
      number: 72,
      category: 'Dringlichkeitsverkehr (Urgency - PAN PAN)',
      title: 'Sprechfunk-Empfangsbestätigung einer Dringlichkeitsmeldung',
      important: 'Relevante Quittierung einer Dringlichkeitsmeldung durch ein Schiff, wenn dieses direkte Hilfe anbieten kann.',
      steps: ['Auf Kanal 16 lauschen.', 'PTT drücken.', 'Sender der Dringlichkeitsmeldung anrufen, Empfang des PAN PAN bestätigen, Position und Hilfemöglichkeiten anbieten.'],
      criteria: 'Phonetisch einwandfreie Sprechfunkquittierung.',
    },
    {
      number: 73,
      category: 'Dringlichkeitsverkehr (Urgency - PAN PAN)',
      title: 'Dringlichkeitsmeldung bei Ausfall der Hauptmaschine in dicht befahrenem Trennungsgebiet',
      important: 'Dringlichkeitsmeldung zur Inanspruchnahme von Schlepphilfe vor Eintritt einer Notlage.',
      steps: ['DSC URGENCY ALL SHIPS senden.', 'Sprechfunk Kanal 16: PAN PAN (3x) ... ENGINE FAILURE IN TRAFFIC SEPARATION SCHEME, REQUIRE TUG ASSISTANCE - OVER.'],
      criteria: 'Situationsbezogene Dringlichkeit ordnungsgemäß übermittelt.',
    },
    {
      number: 74,
      category: 'Dringlichkeitsverkehr (Urgency - PAN PAN)',
      title: 'Annullierung / Beendigung einer Dringlichkeitsmeldung (PAN PAN CANCEL)',
      important: 'Verpflichtende Entwarnung per Sprechfunk an ALL STATIONS, wenn die Dringlichkeitsursache behoben ist.',
      steps: ['Kanal 16 wählen.', 'PTT drücken.', 'Anrufgruppe: PAN PAN (1x) - ALL STATIONS (3x).', 'Absender: THIS IS - Eigener Schiffsname (3x), Rufzeichen (1x), MMSI (1x).', 'Text: PLEASE CANCEL MY PAN PAN MESSAGE OF 1400 UTC, ENGINE RUNNING AGAIN.', 'Abschluss: OUT.'],
      criteria: 'Verwendung des Schlüsselworts CANCEL MY PAN PAN MESSAGE, Beendigung zwingend mit OUT.',
    },
    {
      number: 75,
      category: 'Dringlichkeitsverkehr (Urgency - PAN PAN)',
      title: 'Kanalwechsel von Kanal 16 auf einen Arbeitskanal im Dringlichkeitsverkehr',
      important: 'Freihaltung von Kanal 16 für nachfolgende Notrufe durch Ausweichen auf Schiff-Schiff-Kanäle.',
      steps: ['In der Dringlichkeitsmeldung den Ziel-Arbeitskanal ankündigen (z. B. SWITCH TO VHF CHANNEL 72).', 'Am Funkgerät unmittelbar Kanal 72 anwählen.', 'Lautstärke und Squelch auf Kanal 72 nachjustieren.', 'Funkverkehr dort fortsetzen.'],
      criteria: 'Nahtloser Übergang der Kommunikation auf den Sekundärkanal.',
    },
    {
      number: 76,
      category: 'Dringlichkeitsverkehr (Urgency - PAN PAN)',
      title: 'Abwicklung von Dringlichkeitsverkehr bei gleichzeitigem Notverkehr auf Kanal 16',
      important: 'Ausweichen des Dringlichkeitsanrufs auf Arbeitskanäle, wenn Kanal 16 durch ein MAYDAY gesperrt ist.',
      steps: ['DSC-Anruf URGENCY ALL SHIPS mit zugewiesenem Arbeitskanal auf Kanal 70 aussenden.', 'Sprechfunkmeldung direkt auf dem gewählten Arbeitskanal abgeben.'],
      criteria: 'Störungsfreie Abwicklung abseits der belasteten Notfrequenz.',
    },
    {
      number: 77,
      category: 'Dringlichkeitsverkehr (Urgency - PAN PAN)',
      title: 'Weiterleitung einer Dringlichkeitsmeldung (Urgency Relay)',
      important: 'Weitergabe einer Beobachtung einer fremden Gefahr durch ein drittes Schiff.',
      steps: ['Kanal 16 wählen.', 'PTT drücken.', 'PAN PAN (3x) - ALL STATIONS (3x) - THIS IS - Eigener Name (3x) - FOLLOWING RECEIVED FROM....'],
      criteria: 'Fremde Dringlichkeit regelkonform weitergeleitet.',
    },
    {
      number: 78,
      category: 'Dringlichkeitsverkehr (Urgency - PAN PAN)',
      title: 'Dringlichkeitsmeldung wegen Ausfall des Echolots bei Nacht in Flachwasser',
      important: 'Meldung drohender Grundberührung als Dringlichkeitsfall.',
      steps: ['DSC URGENCY auslösen.', 'Sprechfunk Kanal 16 absetzen.'],
      criteria: 'Korrekter Inhalt bezüglich Navigationshilfeanforderung.',
    },
    {
      number: 79,
      category: 'Dringlichkeitsverkehr (Urgency - PAN PAN)',
      title: 'Dringlichkeitsmeldung bei Wassereinbruch unter eigener Pumpenbeherrschung',
      important: 'Einstufung als PAN PAN (nicht MAYDAY), da die Lage unter Kontrolle ist.',
      steps: ['DSC URGENCY an ALL SHIPS.', 'Sprechfunk: PAN PAN ... WATER LEAKAGE UNDER CONTROL WITH OWN PUMPS, REQUEST STANDBY OF NEARBY SHIPS - OVER.'],
      criteria: 'Richtige Differenzierung der Gefahrenstufe.',
    },
    {
      number: 80,
      category: 'Dringlichkeitsverkehr (Urgency - PAN PAN)',
      title: 'Re-Konditionierung des Geräts nach Beendigung der Dringlichkeit',
      important: 'Wiederherstellung des Standard-Empfangszustands nach Annullierung.',
      steps: ['Rückkehr zu Kanal 16.', 'Kontrolle der DSC-Kanal-70-Wache.'],
      criteria: 'Funkgerät betriebsbereit auf Wache.',
    },
    {
      number: 81,
      category: 'Sicherheitsverkehr (Safety - SECURITE)',
      title: 'Editieren und Senden eines DSC-Sicherheitsanrufs (Safety All Ships)',
      important: 'Digitale Ankündigung von Sicherheitsmeldungen (Wetter, Navigationsgefahren).',
      steps: ['MENU -> DSC CALL -> ALL SHIPS anwählen.', 'Priorität SAFETY auswählen.', 'Arbeitskanal als Sprechfunkkanal festlegen.', 'DSC-Ruf auf Kanal 70 absenden.', 'Das Gerät wechselt auf den angegebenen Kanal oder Kanal 16.'],
      criteria: 'DSC-Ruf mit Priorität SAFETY fehlerfrei übertragen.',
    },
    {
      number: 82,
      category: 'Sicherheitsverkehr (Safety - SECURITE)',
      title: 'Absetzen einer Sicherheitsmeldung per Sprechfunk (Szenario: Unbeleuchtetes Seezeichen)',
      important: 'Abgabe einer Navigationswarnung zum Schutz des Seeverkehrs.',
      steps: ['Sendeleistung 25 W auf Kanal 16 oder Arbeitskanal prüfen.', 'PTT drücken.', 'Sicherheitszeichen: SECURITE (3x gesprochen: SAY-CUR-EE-TAY).', 'Adressat: ALL STATIONS (3x).', 'Absender: THIS IS - Eigener Schiffsname (3x), Rufzeichen (1x).', 'Inhalt: LIGHT BUOY BUXTEHUDE 2 IN POSITION ... UNLIT.', 'Abschluss: OUT.'],
      criteria: 'Dreifaches SECURITE, lückenlose Verortung des Hindernisses, regelkonformer Abschluss mit OUT.',
    },
    {
      number: 83,
      category: 'Sicherheitsverkehr (Safety - SECURITE)',
      title: 'Sprechfunk-Sicherheitsmeldung (Szenario: Treibendes Container-Teil)',
      important: 'Durchgabe konkreter Hinderniskoordinaten.',
      steps: ['Kanal 16 / Arbeitskanal wählen.', 'PTT drücken.', 'SECURITE (3x) - ALL STATIONS (3x) - THIS IS - Eigener Name (3x).', 'FLOATING TIMBER HAZARD TO NAVIGATION IN POSITION ... SHIPS KEPT SHARP LOOKOUT - OUT.'],
      criteria: 'Korrekter Aufbau und Abschluss einer Navigationsmeldung.',
    },
    {
      number: 84,
      category: 'Sicherheitsverkehr (Safety - SECURITE)',
      title: 'Sicherheitsmeldung wegen angekündigtem Starkwind / Sturm',
      important: 'Durchgabe von Wetterwarnungen durch Küstenfunkstellen oder weiterleitende Schiffe.',
      steps: ['Ankündigung per DSC SAFETY auf Kanal 70.', 'Ausweichen auf Arbeitskanal.', 'Sprechfunk: SECURITE ... GALE WARNING FOR GERMAN BIGHT FORCE 8 EXPECTED - OUT.'],
      criteria: 'Wetterwarnung nach Schema übermittelt.',
    },
    {
      number: 85,
      category: 'Sicherheitsverkehr (Safety - SECURITE)',
      title: 'Sicherheitsmeldung wegen Ausfalls eines Hauptnavigationssignals',
      important: 'Information über Systemstörungen im Seegebiet.',
      steps: ['DSC Anruf SAFETY ALL SHIPS.', 'Sprechfunk SECURITE ... DGPS STATION RÜGEN OFF AIR - OUT.'],
      criteria: 'Ordnungsgemäßer Sicherheitsspruch.',
    },
    {
      number: 86,
      category: 'Sicherheitsverkehr (Safety - SECURITE)',
      title: 'Sicherheitsmeldung bezüglich Vermessungsarbeiten oder Kabelverlegearbeiten',
      important: 'Warnung vor eingeschränkt manövrierfähigen Arbeitsschiffen.',
      steps: ['Kanal 16 wählen.', 'PTT drücken: SECURITE (3x) ... CABLE LAYING OPERATIONS BY VESSEL VIKING IN POSITION ... WIDE BERTH REQUESTED - OUT.'],
      criteria: 'Warnhinweis regelkonform verbreitet.',
    },
    {
      number: 87,
      category: 'Sicherheitsverkehr (Safety - SECURITE)',
      title: 'Empfang einer Sicherheitsmeldung und Kanalwechselanweisungen folgen',
      important: 'Nach DSC-Empfang auf den angekündigten Arbeitskanal wechseln.',
      steps: ['DSC-Alarmton am Gerät quittieren (CLEAR).', 'Angezeigten Arbeitskanal am Gerät einstellen.', 'Rauschsperre anpassen und Meldung mitlesen/abfragen.'],
      criteria: 'Richtige Nachführung des Arbeitskanals am Funkgerät.',
    },
    {
      number: 88,
      category: 'Sicherheitsverkehr (Safety - SECURITE)',
      title: 'Annullierung / Aufhebung einer Sicherheitsmeldung (SECURITE CANCEL)',
      important: 'Aufhebung der Warnung, wenn die Gefahr nicht mehr besteht.',
      steps: ['Kanal 16 / Arbeitskanal einstellen.', 'PTT drücken.', 'SECURITE (1x) - ALL STATIONS (3x) - THIS IS - Eigener Name (3x).', 'CANCEL MY SECURITE MESSAGE OF 0800 UTC, DRIFTING CONTAINER HAS BEEN RECOVERED - OUT.'],
      criteria: 'Verwendung von CANCEL MY SECURITE MESSAGE und Beendigung mit OUT.',
    },
    {
      number: 89,
      category: 'Sicherheitsverkehr (Safety - SECURITE)',
      title: 'Sicherheitsmeldung wegen Schießübungen von Marinefahrzeugen',
      important: 'Ankündigung von Sperrgebieten per Sicherheitsfunk.',
      steps: ['DSC SAFETY empfangen.', 'Sprechfunk auf Arbeitskanal abhören und Geokoordinaten des Sperrgebiets notieren.'],
      criteria: 'Exakte Aufzeichnung der Koordinaten der Warnzone.',
    },
    {
      number: 90,
      category: 'Sicherheitsverkehr (Safety - SECURITE)',
      title: 'Sicherheitsmeldung bezüglich Treibeis / Eisgefahr',
      important: 'Sicherheitsmeldung in nordischen Revieren.',
      steps: ['SECURITE (3x) - ALL STATIONS (3x) per Sprechfunk aussenden.', 'Positionsangabe des Eisvorkommens übermitteln.'],
      criteria: 'Korrekter Aufbau nach VO Funk.',
    },
    {
      number: 91,
      category: 'Sicherheitsverkehr (Safety - SECURITE)',
      title: 'Überprüfung der Sendeleistung vor Abgabe einer Sicherheitsmeldung',
      important: 'Sicherheitsmeldungen erfordern stets hohe Sendeleistung (25 W) zur Maximierung der Reichweite.',
      steps: ['Taste HI/LO prüfen.', 'Displaykontrolle auf 25 W.', 'Sicherheitsspruch absenden.'],
      criteria: 'Aussendung erfolgt nachweislich mit 25 W Sendeleistung.',
    },
    {
      number: 92,
      category: 'Sicherheitsverkehr (Safety - SECURITE)',
      title: 'Dokumentation von Empfang und Inhalt von Sicherheitsmeldungen',
      important: 'Schriftliche Fixierung im Schiffstagebuch.',
      steps: ['Inhalt des Spruchs protokollieren.', 'Relevanz für den eigenen Kurs prüfen.'],
      criteria: 'Vollständige Eintragung im Funklogbuch.',
    },
    {
      number: 93,
      category: 'Routineverkehr, Küstenfunkstellen & Gerätesteuerung',
      title: 'Editieren und Senden eines DSC-Routineanrufs an eine Seefunkstelle (Individual Call)',
      important: 'Gezielte digitale Kontaktaufnahme mit einem anderen Schiff unter Angabe eines Arbeitskanals.',
      steps: ['MENU -> DSC CALL -> INDIVIDUAL CALL wählen.', 'Ziel-MMSI manuell eingeben oder aus dem Adressbuch wählen.', 'Intership-Arbeitskanal auswählen (z. B. Kanal 69, 72 oder 77).', 'Call aussenden.', 'Das Gerät wartet auf die DSC-Bestätigung der Gegenstelle und schaltet dann automatisch auf den Arbeitskanal um.'],
      criteria: 'Korrekte Adressierung der fremden MMSI, Auswahl eines gültigen Simplex-Arbeitskanals.',
    },
    {
      number: 94,
      category: 'Routineverkehr, Küstenfunkstellen & Gerätesteuerung',
      title: 'Sprechfunk-Abwicklung eines Routinegesprächs mit einer Seefunkstelle',
      important: 'Standard-Funkgespräch auf dem vereinbarten Arbeitskanal nach erfolgter DSC-Quittierung.',
      steps: ['Sicherstellen, dass der zugewiesene Arbeitskanal aktiv ist.', 'Sendeleistung prüfen (1 W im Nahbereich, 25 W auf Distanz).', 'PTT drücken.', 'Anruf: Schiffsname der Gegenstelle (1-3x), THIS IS (1x), Eigener Schiffsname (1-3x), Rufzeichen (1x).', 'Text: Abgabe der Routinemeldung (z. B. Standortabgleich).', 'Sprechaufforderung: OVER.'],
      criteria: 'Vermeidung von Kanal 16 für das Gespräch, Einhaltung des Anrufschemas, Abschluss mit OVER.',
    },
    {
      number: 95,
      category: 'Routineverkehr, Küstenfunkstellen & Gerätesteuerung',
      title: 'Empfang eines DSC-Routineanrufs und Sprechfunk-Bestätigung auf dem Arbeitskanal',
      important: 'Reaktion des Empfängers auf einen eingehenden Individual Call.',
      steps: ['Eingehenden DSC-Ruf am Display ablesen (MMSI des Anrufers und Arbeitskanal werden angezeigt).', 'Taste ACCEPT / ACK drücken.', 'PTT drücken.', 'Sprechfunkantwort: Anrufername - THIS IS - Eigener Name - READ YOU LOUD AND CLEAR, GO AHEAD - OVER.'],
      criteria: 'DSC-Quittierung am Gerät bestätigt, Einleitung des Sprechfunks auf dem vorgeschriebenen Arbeitskanal.',
    },
    {
      number: 96,
      category: 'Routineverkehr, Küstenfunkstellen & Gerätesteuerung',
      title: 'Editieren und Senden eines DSC-Routineanrufs an eine Küstenfunkstelle',
      important: 'Digitale Kontaktaufnahme mit einer Revierzentrale oder Küstenfunkstelle.',
      steps: ['MENU -> DSC CALL -> COAST STATION CALL ansteuern.', 'MMSI der Küstenfunkstelle (z. B. 002111200) eingeben.', 'Ruf absenden.', 'Umschaltung auf den von der Küstenfunkstelle zugewiesenen Kanal abwarten.'],
      criteria: 'Korrekte Verwendung einer Küstenfunkstellen-MMSI (beginnend mit 00).',
    },
    {
      number: 97,
      category: 'Routineverkehr, Küstenfunkstellen & Gerätesteuerung',
      title: 'Routine-Sprechfunkverkehr mit einer Küstenfunkstelle (Revierzentrale)',
      important: 'Anmeldung beim VTS (Vessel Traffic Service) zur Durchfahrt eines Revierbereichs.',
      steps: ['Vorgeschriebenen Revierkanal einstellen.', 'Sendeleistung bei Bedarf anpassen.', 'PTT drücken.', 'Anruf: JADE TRAFFIC (3x) - THIS IS - Eigener Schiffsname (3x), Rufzeichen (1x).', 'Text: ENTERING REVUE AREA AT BUOY 12, INBOUND FOR WILHELMSHAVEN.', 'Sprechaufforderung: OVER.'],
      criteria: 'Phonetisch korrekte Abwicklung auf dem offiziellen Revierkanal.',
    },
    {
      number: 98,
      category: 'Routineverkehr, Küstenfunkstellen & Gerätesteuerung',
      title: 'Kanalwechsel unter Verwendung der Schnellwahltaste 16/9',
      important: 'Beherrschung der Hardware-Direkttasten am Gerät zur Rückkehr auf den Notkanal.',
      steps: ['Nach Beendigung eines Routinegesprächs die Taste 16/9 betätigen.', 'Displayanzeige verifizieren: Kanal 16 ist sofort wieder aktiv.', 'Squelch- und Lautstärkekontrolle durchführen.'],
      criteria: 'Unverzügliche Wiederherstellung der Hörbereitschaft auf Kanal 16.',
    },
    {
      number: 99,
      category: 'Routineverkehr, Küstenfunkstellen & Gerätesteuerung',
      title: 'Durchführung eines DSC-Selbsttests (DSC Self-Test)',
      important: 'Überprüfung der internen Modems und Funktionen der Funkanlage ohne Abstrahlung eines Signals.',
      steps: ['MENU -> SYSTEM SETUP -> TEST / DSC TEST aufrufen.', 'Eigene MMSI als Testziel selektieren oder geräteinternen Loopback-Test wählen.', 'Test ausführen und Systemmeldung TEST OK verifizieren.'],
      criteria: 'Durchführung eines geräteinternen Tests ohne Aussendung von HF-Energie auf Kanal 70.',
    },
    {
      number: 100,
      category: 'Routineverkehr, Küstenfunkstellen & Gerätesteuerung',
      title: 'Abfrage des DSC-Empfangsspeichers für Routineanrufe',
      important: 'Nachträgliches Auslesen verpasster Routineanrufe im Gerät.',
      steps: ['Menü CALL LOG -> ROUTINE LOG öffnen.', 'Eintragsliste durchblättern.', 'MMSI des Anrufers, Zeitstempel und vorgeschlagenen Kanal ermitteln.'],
      criteria: 'Vollständiges Auslesen der Verbindungsdaten aus dem Protokollspeicher.',
    },
    {
      number: 101,
      category: 'Routineverkehr, Küstenfunkstellen & Gerätesteuerung',
      title: 'Verwendung des internationalen Phonetischen Alphabets (NATO-Alphabet)',
      important: 'Fehlerfreie Buchstabierung von Eigennamen, Rufzeichen und Positionsdaten bei schlechten Empfangsbedingungen.',
      steps: ['PTT drücken.', 'Buchstabierung ankündigen: I SPELL....', 'Eigennamen phonetisch buchstabieren (z. B. DECKER -> DELTA ECHO CHARLIE KILO ECHO ROMEO).'],
      criteria: '100 % fehlerfreie Verwendung der offiziellen NATO-Buchstabierbegriffe.',
    },
    {
      number: 102,
      category: 'Routineverkehr, Küstenfunkstellen & Gerätesteuerung',
      title: 'Übermittlung von Zahlenfolgen im Sprechfunkverkehr',
      important: 'Richtige Sprechweise von Zahlen und Positionen im Seefunk.',
      steps: ['PTT drücken.', 'Geokoordinaten als Einzelziffern aussprechen (z. B. 54^\\circ 03\' N -> FIVE FOUR DEGREES ZERO THREE MINUTES NORTH).'],
      criteria: 'Vermeidung von zusammengesetzten Zahlworten, strikte Nutzung von Einzelziffern.',
    },
    {
      number: 103,
      category: 'Routineverkehr, Küstenfunkstellen & Gerätesteuerung',
      title: 'Beendigung eines Routinefunkverkehrs (Abschluss mit OUT)',
      important: 'Prozeduraler Beendigungsbefehl nach Abschluss des Informationsaustauschs.',
      steps: ['Letzten Satz im Routinegespräch sprechen.', 'Beendigungsphrase anfügen: EIGENER SCHIFFSNAME - OUT.', 'PTT loslassen.', 'Gerät auf Kanal 16 zurückstellen.'],
      criteria: 'Verwendung des Worts OUT zur Signalisierung, dass keine Antwort mehr erwartet wird.',
    },
    {
      number: 104,
      category: 'Routineverkehr, Küstenfunkstellen & Gerätesteuerung',
      title: 'Umschalten auf Hafenfunkkanäle / Nautische Auskunftsfunkstellen',
      important: 'Manuelle Anwahl spezifischer Hafenfunkkanäle im Nahbereich.',
      steps: ['Geforderten Kanal (z. B. Kanal 11 für Port Control) wählen.', 'Sendeleistung auf 1 W reduzieren.', 'Squelch prüfen.'],
      criteria: 'Hafenkanal mit verminderter Sendeleistung betriebsbereit.',
    },
    {
      number: 105,
      category: 'Routineverkehr, Küstenfunkstellen & Gerätesteuerung',
      title: 'Wiederherstellung der dauerhaften Überwachung von Kanal 16 und Kanal 70',
      important: 'Das Funkgerät nach Beendigung aller Aufgaben in den normkonformen GMDSS-Standby-Zustand versetzen.',
      steps: ['Kanal 16 im Hauptdisplay einstellen.', 'Sendeleistung auf 25 W zurücksetzen.', 'Lautstärke auf Raumpegel einstellen.', 'Squelch an der Rauschgrenze arretieren.', 'Verifizieren, dass der DSC-Wachempfänger aktiv auf Kanal 70 mithört.'],
      criteria: 'Das VHF-DSC-System erfüllt 100 % der gesetzlichen Vorgaben für die Wache im Seefunkdienst.',
    },
  ];
})(window);
